{{ if .Values.VICTORIA_USER -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "log-exporter.fullname" . }}-victoria-credentials
  labels:
    {{- $name := printf "%s-victoria-credentials" (include "log-exporter.fullname" .) -}}
    {{- include "log-exporter.resourceLabels" (dict "ctx" . "name" $name) | nindent 4 }}
data:
  VICTORIA_USER: {{ .Values.VICTORIA_USER | b64enc }}
  VICTORIA_PASSWORD: {{ .Values.VICTORIA_PASSWORD | b64enc }}
{{ end -}}
