{{ if .Values.PROMRW_USER -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "log-exporter.fullname" . }}-promrw-credentials
  labels:
    {{- $name := printf "%s-promrw-credentials" (include "log-exporter.fullname" .) -}}
    {{- include "log-exporter.resourceLabels" (dict "ctx" . "name" $name) | nindent 4 }}
data:
  PROMRW_USER: {{ .Values.PROMRW_USER | b64enc }}
  PROMRW_PASSWORD: {{ .Values.PROMRW_PASSWORD | b64enc }}
{{ end -}}
