{{- if eq .Values.LME_MODE "pull" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: {{ .Values.NAMESPACE }}
  labels:
    {{- $name := printf "%s-monitor" (include "log-exporter.fullname" .) -}}
    {{- include "log-exporter.resourceLabels" (dict "ctx" . "name" $name "processedByOperator" "prometheus-operator") | nindent 4 }}
    k8s-app: {{ include "log-exporter.fullname" . }}-monitor
  name: {{ include "log-exporter.fullname" . }}-monitor
spec:
  endpoints:
  - port: "http"
    scheme: http
    path: "/metrics"
    interval: 1m
    scrapeTimeout: 10s
  jobLabel: k8s-app
  selector:
    matchLabels:
      app: {{ include "log-exporter.fullname" . | quote }}
  namespaceSelector:
    matchNames:
      - {{ .Values.NAMESPACE }}
{{ end -}}
