{{ if eq "loki" (lower .Values.LME_DATASOURCE_TYPE) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: log-exporter-loki-credentials
  labels:
    app.kubernetes.io/part-of: '{{ .Values.LME_APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: saasDeployer
data:
  LOKI_USER: {{ .Values.LME_LOKI_USER | b64enc }}
  LOKI_PASSWORD: {{ .Values.LME_LOKI_PASSWORD | b64enc }}
{{ end -}}