{{ if eq "newrelic" (lower .Values.LME_DATASOURCE_TYPE) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: log-exporter-newrelic-credentials
  labels:
    app.kubernetes.io/part-of: '{{ .Values.LME_APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: saasDeployer
data:
  NEWRELIC_ACCOUNT_ID: {{ .Values.LME_NEWRELIC_ACCOUNT_ID | int64 | print | b64enc }}
  NEWRELIC_X_QUERY_KEY: {{ .Values.LME_NEWRELIC_X_QUERY_KEY | print | b64enc }}
{{ end -}}